spring:
  application:
    name: example
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

      config:
        server-addr: 127.0.0.1:8848
        prefix: example
        file-extension: properties
